export const FETCHING_SURAH_LIST_START = "FETCHING_SURAH_LIST_START"
export const FETCHING_SURAH_LIST_SUCCESS = "FETCHING_SURAH_LIST_SUCCESS"
export const FETCHING_SURAH_LIST_FAILED = "FETCHING_SURAH_LIST_FAILED"