export const FETCHING_SURAH_LIST_START = "FETCHING_SURAH_LIST_START"
export const FETCHING_SURAH_LIST_SUCCESS = "FETCHING_SURAH_LIST_SUCCESS"
export const FETCHING_SURAH_LIST_FAILED = "FETCHING_SURAH_LIST_FAILED"

export const FETCHING_VERSES_START = "FETCHING_VERSES_START"
export const FETCHING_VERSES_SUCCESS = "FETCHING_VERSES_SUCCESS"
export const FETCHING_VERSES_FAILED = "FETCHING_VERSES_FAILED"
export const SETTING_ARABIC_FONT = "SETTING_ARABIC_FONT"

